### ISSUE TITLE
Wrong version in package.json

### ISSUE THREAD

**Issue by semanticfire** [rdf-ext/rdf-ext-dist-builder#10]
The develop branch has the wrong version of package.json resulting in confusing pacakge names.

**Comment by bergos** [comment]
Fixed the version. If you use the `./dump-version` script, you also get a es5 build using `babel-cli`. Web interface update is in progress.

**Comment by semanticfire** [comment]
after a pull I get:

```
TypeError: Path must be a string. Received [ '/tmp/tmp-21647Fa48AighNEgl', [Function: _cleanupCallback] ]
    at assertPath (path.js:28:11)
    at Object.join (path.js:1232:7)
    at /home/bart/git/rdf-ext-dist-builder/index.js:66:34
    at tryCatcher (/home/bart/git/rdf-ext-dist-builder/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/bart/git/rdf-ext-dist-builder/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/home/bart/git/rdf-ext-dist-builder/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/home/bart/git/rdf-ext-dist-builder/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/home/bart/git/rdf-ext-dist-builder/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/bart/git/rdf-ext-dist-builder/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/bart/git/rdf-ext-dist-builder/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:800:20)
    at tryOnImmediate (timers.js:762:5)
    at processImmediate [as _immediateCallback] (timers.js:733:5)

```

**Comment by ktk** [comment]
@bergos with the script I get:

```
created distribution: 2906kb
[BABEL] Note: The code generator has deoptimised the styling of "rdf-ext-all-1.0.0.src.js" as it exceeds the max of "500KB".
rm: public/dist/rdf-ext-all-latest.min.js.ap: No such file or directory
ln: public/dist/rdf-ext-all-latest.min.js.map: File exists
```

still builds from what I can see

**Comment by bergos** [comment]
@semanticfire remove the existing `node_modules` folder and run `npm install` again. The interface of the `tmp` package changed.

**Comment by semanticfire** [comment]
Tried that, didnt help

**Comment by bergos** [comment]
Web interface is now running again: [rdf-ext.zazuko.com](http://rdf-ext.zazuko.com/)
